# This file was generated by GoReleaser. DO NOT EDIT.
cask "bruce-test-api" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "0afcfdfc15769e0f0c1fc2714ee6ed4c3603b8431aee0e36616e11e935d43735"
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "ece2a925cbbfddd4adc2413a2f55445c2eeaf01939a70229ca4276bd8a47f8b0"
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "40b166c8a363d408591f1168d3695ab67a09171c3671848938f608c0ea49812b"
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f9a60eb933ff6e9616dec3cd012fe56ed4d119c713cd9b2c13e44b7455eb2a1"
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bruce-test-api"
  desc "The best test CLI."
  homepage "https://bruce-hill.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bruce-test-api"
  manpage "man/man1/bruce-test-api.1.gz"
  bash_completion "completions/bruce-test-api.bash"
  fish_completion "completions/bruce-test-api.fish"
  zsh_completion "completions/bruce-test-api.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bruce-test-api"]
    end
  end

  # No zap stanza required

end
