# This file was generated by GoReleaser. DO NOT EDIT.
cask "bruce-test-api" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_macos_amd64.zip"
      sha256 "8879a770c879338992e91641b59d83664e1c78bd7ff27201e4119ee11f9ad9d4"
    end
    on_arm do
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_macos_arm64.zip"
      sha256 "60182e978aa6cdd95c0696cf55c5eabff905324932e0c0ade1027ca0bd126ec9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_linux_amd64.tar.gz"
      sha256 "ff0c7d12ebd7d8039ab9623ea4d013c80e3d823a1b8e8b2322ff0c3725d89ce0"
    end
    on_arm do
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_linux_arm64.tar.gz"
      sha256 "b4467c79ba8bf55d4e732312612ab98861c3bae7d1aaf8eb490db5eea2204c10"
    end
  end

  name "bruce-test-api"
  desc "The best test CLI."
  homepage "https://bruce-hill.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bruce-test-api"
  manpage "man/man1/bruce-test-api.1.gz"
  bash_completion "completions/bruce-test-api.bash"
  fish_completion "completions/bruce-test-api.fish"
  zsh_completion "completions/bruce-test-api.zsh"

  # No zap stanza required

end
