# This file was generated by GoReleaser. DO NOT EDIT.
cask "bruce-test-api" do
  name "bruce-test-api"
  desc "The best test CLI."
  homepage "https://bruce-hill.com"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bruce-test-api"
  manpage "man/man1/bruce-test-api.1.gz"
  bash_completion "completions/bruce-test-api.bash"
  zsh_completion "completions/bruce-test-api.zsh"
  fish_completion "completions/bruce-test-api.fish"

  on_macos do
    on_intel do
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_macos_amd64.zip"
      sha256 "c32bec02df896d4553cee51b1e10c14c02e32d04e01e0ed8bd98793ed232491d"
    end
    on_arm do
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_macos_arm64.zip"
      sha256 "0184e1caf53a2beefb241d78d055b8ed4ce14ac32c31d1427b7f3aceb8a41141"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_linux_amd64.tar.gz"
      sha256 "27a2ffe06b60290efb81ebb2665dd1eff7c6535e71fe353e41ed9d514489e11d"
    end
    on_arm do
      url "https://github.com/bruce-hill/bruce-test-api-cli/releases/download/v#{version}/bruce-test-api_#{version}_linux_arm64.tar.gz"
      sha256 "7eef24c0a7aa60b896e9171eee964d190796347144c8768b10d5188d54772ce3"
    end
  end

  # No zap stanza required
end
